dataformCoreVersion: 3.0.0-beta.4
defaultProject: dataform-imdb
defaultLocation: us-central1
defaultDataset: imdb
defaultAssertionDataset: imdb_assertions
vars:
    LOAD_GCS_BUCKET: imdb-data/imdb
    RAW_DATA: imdb_staging
    TARGET_DATA: imdb
